# Generated by Django 3.0.6 on 2020-05-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=255)),
                ('menh', models.CharField(default='', max_length=255)),
                ('van', models.CharField(default='', max_length=255)),
                ('gioitinh', models.CharField(default='', max_length=255)),
                ('lastname', models.CharField(default='', max_length=255)),
                ('meaning', models.CharField(blank=True, default='', max_length=1024)),
            ],
        ),
    ]
