# Generated by Django 3.0.6 on 2020-06-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0002_name_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenlot', models.CharField(default='', max_length=255)),
                ('menh', models.CharField(default='', max_length=255)),
                ('gioitinh', models.CharField(default='', max_length=255)),
                ('meaning', models.CharField(blank=True, default='', max_length=1024)),
            ],
        ),
    ]
