# Generated by Django 3.0.6 on 2020-06-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0003_midname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midname',
            name='gioitinh',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='midname',
            name='meaning',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='midname',
            name='menh',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='midname',
            name='tenlot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
